import streamlit as st
from urllib.parse import urlparse, parse_qs

from agent_core.agent_client import summarize_youtube_video, summarize_for_platform
from agent_core import auth_manager
from agent_core.twitter_tool import post_to_twitter, TwitterAPIError, TwitterAuthError, TwitterRateLimitError

# --- Page Configuration ---
st.set_page_config(page_title="YouTube Summarizer", page_icon="📺", layout="wide")

# --- Session State Initialization ---
if "twitter_token" not in st.session_state:
    st.session_state["twitter_token"] = None
if "linkedin_token" not in st.session_state:
    st.session_state["linkedin_token"] = None
if "twitter_auth_url" not in st.session_state:
    st.session_state["twitter_auth_url"] = None
if "pending_post" not in st.session_state:
    st.session_state["pending_post"] = None  # Stores the generated post awaiting confirmation

# --- OAuth Callback Handler ---
query_params = st.query_params
if "code" in query_params:
    state = query_params.get("state")
    if isinstance(state, list):
        state = state[0]
        
    verifier = auth_manager.get_verifier_from_state(state) if state else None
    
    if verifier:
        try:
            code = query_params["code"]
            if isinstance(code, list):
                code = code[0]
                
            token_response = auth_manager.exchange_code_for_token(
                "twitter",
                code,
                verifier
            )
            st.session_state["twitter_token"] = token_response
            st.session_state["twitter_auth_url"] = None
            st.query_params.clear()
            st.success("🎉 Successfully connected to Twitter!")
            st.rerun()
        except auth_manager.AuthError as e:
            st.error(f"Authentication failed: {e}")
            st.query_params.clear()
    else:
        if not st.session_state.get("twitter_token"):
            st.warning("⚠️ Authentication session expired. Please try logging in again.")
        st.query_params.clear()

# --- Sidebar: Authentication ---
with st.sidebar:
    st.header("🔐 Connect Accounts")
    
    # Twitter Authentication
    if not auth_manager.is_authenticated("twitter", st.session_state):
        # Pre-generate auth URL if not present
        if not st.session_state.get("twitter_auth_url"):
            try:
                auth_url, state = auth_manager.get_oauth_url("twitter")
                st.session_state["twitter_auth_url"] = auth_url
            except Exception as e:
                st.error(f"Error initializing login: {e}")
        
        # Direct redirect button
        if st.session_state.get("twitter_auth_url"):
            st.link_button("🐦 Login with Twitter", st.session_state["twitter_auth_url"], use_container_width=True)
    else:
        st.success("✓ Twitter connected")
        if st.button("Logout Twitter", use_container_width=True):
            token = auth_manager.get_access_token("twitter", st.session_state)
            if token:
                auth_manager.revoke_token("twitter", token)
            st.session_state["twitter_token"] = None
            st.session_state["twitter_auth_url"] = None
            st.session_state["pending_post"] = None
            st.rerun()
    
    st.divider()
    st.caption("ℹ️ Twitter allows ~50 tweets per 24 hours")

# --- Main Content ---
st.title("📺 YouTube Video Summarizer")
st.write("Enter a YouTube URL below to get a concise summary generated by an AI agent.")

def clear_input():
    st.session_state["youtube_url"] = ""
    st.session_state["pending_post"] = None

def cancel_post():
    st.session_state["pending_post"] = None

# --- Confirmation Flow: If there's a pending post, show confirmation UI ---
if st.session_state.get("pending_post"):
    pending = st.session_state["pending_post"]
    
    st.markdown("---")
    st.subheader("📝 Proposed Post")
    st.info(pending["text"])
    st.markdown(f"**Character count:** {len(pending['text'])}/280")
    
    # Custom CSS for the Post button color (pale green)
    st.markdown("""
        <style>
        /* Target the first button in the confirmation container */
        div.stButton > button[kind="primary"] {
            background-color: #c8e6c9 !important;
            color: #1b5e20 !important;
            border: 1px solid #a5d6a7 !important;
        }
        div.stButton > button[kind="primary"]:hover {
            background-color: #a5d6a7 !important;
            border-color: #81c784 !important;
        }
        </style>
    """, unsafe_allow_html=True)
    
    col1, col2 = st.columns(2)
    with col1:
        if st.button("✅ Post to Twitter", type="primary", use_container_width=True):
            with st.spinner("Posting..."):
                try:
                    token = auth_manager.get_access_token("twitter", st.session_state)
                    result = post_to_twitter(pending["text"], token)
                    tweet_id = result.get("data", {}).get("id")
                    st.success(f"✅ Posted! [View tweet](https://twitter.com/i/web/status/{tweet_id})")
                    st.session_state["pending_post"] = None
                except TwitterAuthError as e:
                    st.error(f"🔒 {e}")
                    st.session_state["twitter_token"] = None
                    st.session_state["pending_post"] = None
                except TwitterRateLimitError as e:
                    st.error(f"⏱️ {e}")
                except (TwitterAPIError, ValueError) as e:
                    st.error(f"❌ Failed: {e}")
    with col2:
        if st.button("❌ Cancel", use_container_width=True, on_click=cancel_post):
            pass  # on_click handles this
    
    st.stop()  # Don't show the rest of the UI while confirming

# --- Normal Input Flow ---
youtube_url = st.text_input(
    "YouTube URL", 
    placeholder="https://www.youtube.com/watch?v=...", 
    key="youtube_url"
)

platform_options = ["Default", "Twitter"]
selected_platform = st.selectbox(
    "Summary Format",
    options=platform_options,
    index=0,
    help="Select target platform for optimized summary format"
)

platform_map = {"Default": "default", "Twitter": "twitter"}
platform = platform_map.get(selected_platform, "default")

if platform == "twitter":
    st.info("🐦 Twitter mode: Summary will be tiny to fit URL and hashtags.")
    if not auth_manager.is_authenticated("twitter", st.session_state):
        st.warning("⚠️ Connect in sidebar to post directly.")

col1, col2, col3 = st.columns([2, 2, 1])
with col1:
    summarize_only = st.button("📝 Summarize Video", type="primary")
with col2:
    can_post = platform == "twitter" and auth_manager.is_authenticated("twitter", st.session_state)
    summarize_and_post = st.button(
        "📝 Summarize & Post",
        disabled=not can_post,
        help="Generate & post to Twitter" if can_post else "Login to Twitter first"
    )
with col3:
    st.button("🔄 Reset", on_click=clear_input)

if summarize_only or summarize_and_post:
    if not youtube_url:
        st.error("Please enter a valid YouTube URL.")
    else:
        with st.spinner("Processing..."):
            try:
                if platform == "default":
                    summary = summarize_youtube_video(youtube_url)
                    st.success("Generated Successfully!")
                    st.markdown(f"### Summary\n{summary}")
                else:
                    summary = summarize_for_platform(youtube_url, platform)
                    
                    # Build final tweet
                    hashtags = " #AI #Summary"
                    url_length = 23  # Twitter standard
                    
                    char_count = len(summary) + len(hashtags) + 1 + url_length
                    
                    if char_count > 280:
                        max_summary_len = 280 - len(hashtags) - 24 - 3 
                        summary = summary[:max_summary_len] + "..."
                        st.warning("⚠️ Summary truncated to fit Twitter limit.")
                    
                    final_post = f"{summary}{hashtags} {youtube_url}"
                    
                    if summarize_and_post:
                        # Store for confirmation
                        st.session_state["pending_post"] = {"text": final_post, "url": youtube_url}
                        st.rerun()
                    else:
                        # Just display
                        st.success("Generated Successfully!")
                        color = "green" if len(final_post) <= 280 else "red"
                        st.markdown(f"**Character count:** :{color}[{len(final_post)}/280]")
                        st.markdown(f"### Proposed Post\n{final_post}")
                        
            except Exception as e:
                st.error(f"An error occurred: {e}")