import streamlit as st
from agent_core.agent_client import summarize_youtube_video

st.set_page_config(page_title="YouTube Summarizer", page_icon="📺")

st.title("📺 YouTube Video Summarizer")
st.write("Enter a YouTube URL below to get a concise summary generated by an AI agent.")

def clear_input():
    st.session_state["youtube_url"] = ""

youtube_url = st.text_input("YouTube URL", placeholder="https://www.youtube.com/watch?v=...", key="youtube_url")

col1, col2 = st.columns([1, 3])
with col1:
    submit = st.button("Summarize Video", type="primary")
with col2:
    st.button("Reset", on_click=clear_input)

if submit:
    if not youtube_url:
        st.error("Please enter a valid YouTube URL.")
    else:
        with st.spinner("Processing video transcript and generating summary..."):
            try:
                # Call the agent client function
                summary = summarize_youtube_video(youtube_url)
                st.success("Summary generated successfully!")
                st.markdown(summary)
            except Exception as e:
                st.error(f"An error occurred: {e}")